language: node_js
notifications:
  email: rafaelamaralmario@gmail.com
node_js:
  - "12.18.2"
services:
- postgresql
env:
  global:
  - NODE_ENV: test
  - TRAVIS: true
addons:
  postgresql: '12.2'
before_script:
- pg_lsclusters
- psql -c 'create database ts_api_test;' -U postgres
- npm i -g sequelize-cli gulp-cli
- cd src/server/
- sequelize db:migrate --env test
- npm install
- cd ../../
- gulp
- cd src/server/
script:
- npm run unit-test
- npm run integration-test
