sudo: required
language: node_js
notifications:
  email: rafaelamaralmario@gmail.com
node_js:
  - 12.18.2
services:
  - postgresql
env:
  global:
    - NODE_ENV: test
    - TRAVIS: true
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database ts_api_test;' -U postgres
  - npm i -g sequelize-cli gulp-cli
  - cd src/server/
  - sequelize db:migrate --env test
  - yarn install
  - gulp
script:
  - yarn unit-test
  - yarn run integration-test
